# Only for building testing version by Github CI workflow

name: DOOM3/Quake4/Prey Windows x64 MSVC CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Q3E/src/main/jni/doom3/neo/**'
      - '.github/workflows/doom3_windows_x64_msvc.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Q3E/src/main/jni/doom3/neo/**'
      - '.github/workflows/doom3_windows_x64_msvc.yml'

jobs:
  build-doom3-windows-x64-msvc:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.2"

    - name: Setup vcpkg and install depends
      uses: johnwason/vcpkg-action@v6
      with:
        pkgs: 'SDL2 curl openal-soft zlib'
        triplet: x64-windows
        token: ${{ secrets.TOKEN }}
        github-binarycache: true

    - name: Configure project with CMake
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt

    - name: Build with Ninja
      run: |
        cmake --build . --config Release

    - name: Copy OpenAL32.dll
      run: |
        xcopy /Y/Q ${{ github.workspace }}\vcpkg\packages\openal-soft_x64-windows\bin\OpenAL32.dll Q3E\src\main\jni\doom3\neo\Release\

    - name: Get current date time
      id: current_datetime
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD_HH-mm-ss"

    - name: Prepare package
      id: prepare_package
      run: |
        dir Q3E\src\main\jni\doom3\neo\Release
        mkdir Release
        xcopy /Y/Q Q3E\src\main\jni\doom3\neo\Release\*.dll windows_x64_release\
        xcopy /Y/Q Q3E\src\main\jni\doom3\neo\Release\*.exe windows_x64_release\
        dir windows_x64_release
# echo ::set-env name=ZIP_FILE value=idTech4A++-test_windows_x64_release-${{ steps.current_datetime.outputs.time }}.zip

    - name: Package
      uses: vimtor/action-zip@v1.2
      with:
        files: windows_x64_release/
        dest: idTech4A++-test_windows_x64_release-${{ steps.current_datetime.outputs.time }}.zip
        recursive: false

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: windows_x64_testing
        delete_release: true
        repo: glKarin/com.n0n3m4.diii4a
        github_token: ${{ secrets.TOKEN }}

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "windows_x64_testing"
        prerelease: true
        title: "Windows x64 testing (Non-release. Automatic CI builds)"
        files: |
          idTech4A++-test_windows_x64_release-${{ steps.current_datetime.outputs.time }}.zip
